client: client.c
	g++ -o webtest client.c



run:
	./webtest bioresearch.byu.edu 80 /CS360/foo.html 100

run-debug:
	./webtest bioresearch.byu.edu 80 /CS360/foo.html -d 100

clean:
	rm -r webtest